CREATE DATABASE IF NOT EXISTS cellar;

USE cellar;

CREATE TABLE IF NOT EXISTS object (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name varchar(255) NOT NULL,
    path TEXT NOT NULL,
    file BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS file (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    object_id BIGINT UNSIGNED NOT NULL,
    content TEXT NOT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    is_final BOOLEAN NOT NULL DEFAULT 0,
    FOREIGN KEY (object_id) REFERENCES object(id)
);
